from core.text import extract_titles

sections = [
    """
## PROTOCOL AMENDMENT SUMMARY OF CHANGES TABLE

| DOCUMENTHISTORY   | DOCUMENTHISTORY   |
|-------------------|-------------------|
| Document          | Date              |
| Amendment 6       | 19 February 2021  |
| Amendment 5       | 18 January 2021   |
| Amendment 4       | 14 December 2020  |
| Amendment 3       | 26 October 2020   |
| Amendment 2       | 17 September 2020 |
| Amendment 1       | 10 August 2020    |
| Original Protocol | 15 July 2020      |

""",
    """
## Overall Rationale for the Amendment:

The principal reason for this amendment was to remove the extended dosing interval assessment and to remove adolescents from the study population that were added to Amendment 5. (Note: Amendment 5 was not implemented.)

| Section # and Name                                                                                                                                                                                                               | Description of Change                                                                               | Brief Rationale                                                    | Substantial/ Non-substantial   |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|--------------------------------------------------------------------|--------------------------------|
| Title Page, 1.1 Synopsis                                                                                                                                                                                                         | Removed 'and Adolescents' from the title                                                            | Given removal of adolescents from the study population             | Substantial                    |
| 1.1 Synopsis, 2.1 Study Rationale                                                                                                                                                                                                | Removed text from the study rationale regarding adolescents                                         | Given removal of adolescents from the study population             | Substantial                    |
| 1.1 Synopsis                                                                                                                                                                                                                     | Reduced the number of study sites from 300 to 150                                                   | To more realistically align with the actual number of sites        | Non-substantial                |
| 1.1 Synopsis, 3 Objective and Endpoints, Appendix F (Table 15)                                                                                                                                                                   | Upgraded exploratory endpoint 5 to secondary endpoint 9                                             | To gain information on efficacy following a single dose of AZD1222 | Substantial                    |
| 1.1 Synopsis, 1.2 Schema, 1.3 Schedule of Activities 3 Objectives and Endpoints, 4.1 Overall Design, 4.2 Scientific Rationale for Study Design,                                                                                  | Removed Appendix GPart 2 and any cross-references to Appendix GPart 2                               | Given removal of Part 2 from the protocol                          | Substantial                    |
| 4.3 Justification for Dose, 4.4 End of Study Definition, 5 Study Population, 6.1.2 Dosing Instructions, 6.3 Measures to Minimize Bias: Randomization and Blinding, 7.1 Discontinuation of Study Intervention 8 Study Assessments | Removed the 'Part 1' label from the main study and corresponding substudy and immunogenicity cohort |                                                                    | Substantial                    |

| Section # and Name                                                                                       | Description of Change                                                                                                                                                                                                                                                            | Brief Rationale                                                                                                                                                        | Substantial/ Non-substantial   |
|----------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------|
| and Procedures, 9 Statistical Considerations, Appendix G Part 2                                          |                                                                                                                                                                                                                                                                                  |                                                                                                                                                                        |                                |
| 1.1 Synopsis, Appendix F (Table 15)                                                                      | Removed specification that primary objective 3 and secondary objectives 7-8 apply to both Part 1 and Part 2                                                                                                                                                                      | Given removal of Part 2 from the protocol                                                                                                                              | Substantial                    |
| 3 Objectives and Endpoints                                                                               | Removed specification that primary objective 3, secondary objectives 7-8, and exploratory objectives 5-13 apply to both Part 1 and Part 2                                                                                                                                        | Given removal of Part 2 from the protocol                                                                                                                              | Substantial                    |
| 3 Objectives and Endpoints                                                                               | Removed footnote d from Table 5 that indicated exploratory endpoint 5 is an exploratory endpoint for Part 1, but a secondary endpoint for Part 2                                                                                                                                 | Given removal of Part 2 from the protocol                                                                                                                              | Substantial                    |
| 4.2.2 Rationale for Study Endpoints, 8.3.9 Adverse Events of Special Interest, 11 References, Appendix E | Removed the Serazin et al 2020 and Vogel et al 2020 references                                                                                                                                                                                                                   | Given removal of the multisystem inflammatory syndrome in children and adults (MIS-C/A) and acute respiratory distress syndrome (ARDS) terms from Appendix E, Table 13 | Non-substantial                |
| 8.1.2.1 SARS-CoV-2 Testing and Other Virology Assessments                                                | Added text to explain that genotypic evaluation of SARS-CoV-2 is planned at Days 1 and 14 illness visits but may be performed at Days 21 and 28 illness visits based upon logistical constraints, safety signals, or emerging data on efficacy of AZD1222 against viral variants | Clarification                                                                                                                                                          | Non-substantial                |
| 9.4.2.2 Secondary Endpoints, Appendix F (Table 15)                                                       | Revised the list of secondary endpoints to align with the Synopsis and Section 3 of the protocol                                                                                                                                                                                 | Consistency                                                                                                                                                            | Non-substantial                |

| Section # and Name     | Description of Change                 | Brief Rationale                                                    | Substantial/ Non-substantial   |
|------------------------|---------------------------------------|--------------------------------------------------------------------|--------------------------------|
| A5 Committee Structure | Revised this section                  | To align with the current version of the statistical analysis plan | Non-substantial                |
| Appendix E (Table 13)  | Removed reference to MIS-C/A and ARDS | Given removal of the adolescent population                         | Non-substantial                |
| Appendix G Part 2      | Removed this appendix                 | Given removal of Part 2 from the protocol                          | Substantial                    |
| Throughout             | Minor editorial revisions             | Minor, therefore, were not summarized                              | Non-substantial                |
""",
    """
## TABLE OF CONTENTS

| PROTOCOL AMENDMENT SUMMARY OF CHANGES TABLE....................................3                                         | PROTOCOL AMENDMENT SUMMARY OF CHANGES TABLE....................................3                                         |                                                                                                  |
|--------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------|
| TABLE OF CONTENTS......................................................................................................7 | TABLE OF CONTENTS......................................................................................................7 |                                                                                                  |
| 1                                                                                                                        | PROTOCOL SUMMARY................................................................................                         | 12                                                                                               |
| 1.1                                                                                                                      | Synopsis ...........................................................................................................     | 12                                                                                               |
| 1.2                                                                                                                      | Schema.............................................................................................................      | 18                                                                                               |
| 1.3                                                                                                                      | Schedule of Activities .......................................................................................           | 18                                                                                               |
| 2                                                                                                                        | INTRODUCTION............................................................................................                 | 27                                                                                               |
| 2.1                                                                                                                      | Study Rationale ................................................................................................         | 27                                                                                               |
| 2.2                                                                                                                      | Background ......................................................................................................        | 27                                                                                               |
| 2.3                                                                                                                      | Benefit/Risk Assessment...................................................................................               | 29                                                                                               |
| 2.3.1                                                                                                                    | Risk Assessment...............................................................................................           | 30                                                                                               |
| 2.3.2                                                                                                                    | Benefit Assessment...........................................................................................            | 30                                                                                               |
| 2.3.3                                                                                                                    | Overall Benefit: Risk Conclusion......................................................................                   | 30                                                                                               |
| 3                                                                                                                        | OBJECTIVES AND ENDPOINTS...................................................................                              | 30                                                                                               |
| 4                                                                                                                        | STUDY DESIGN.............................................................................................                | 34                                                                                               |
| 4.1                                                                                                                      | Overall Design..................................................................................................         | 34                                                                                               |
| 4.2                                                                                                                      | Scientific Rationale for Study Design                                                                                    | ............................................................... 36                               |
| 4.2.1                                                                                                                    | Rationale for Study Design and Participant Population .....................................                              | 36                                                                                               |
| 4.2.2                                                                                                                    | Rationale for Study Endpoints ..........................................................................                 | 37                                                                                               |
| 4.3                                                                                                                      | Justification for Dose........................................................................................           | 37                                                                                               |
| 4.4                                                                                                                      | End of Study Definition ....................................................................................             | 38                                                                                               |
| 5                                                                                                                        | STUDY POPULATION...................................................................................                      | 39                                                                                               |
| 5.1                                                                                                                      | Inclusion Criteria ..............................................................................................        | 39                                                                                               |
| 5.2                                                                                                                      | Exclusion Criteria                                                                                                       | ............................................................................................. 41 |
| 5.3                                                                                                                      | Lifestyle Considerations ...................................................................................             | 42                                                                                               |
| 5.4                                                                                                                      | Screen Failures .................................................................................................        | 42                                                                                               |
| 6                                                                                                                        | STUDY INTERVENTION...............................................................................                        | 43                                                                                               |
| 6.1                                                                                                                      | Study Interventions Administered.....................................................................                    | 43                                                                                               |
| 6.1.1                                                                                                                    | Investigational Products....................................................................................             | 43                                                                                               |
| 6.1.2                                                                                                                    | Dosing Instructions...........................................................................................           | 44                                                                                               |
| 6.2                                                                                                                      | Preparation/Handling/Storage/Accountability ...................................................                          | 44                                                                                               |
| 6.2.1.1                                                                                                                  | AZD1222..........................................................................................................        | 45                                                                                               |
| 6.2.1.2                                                                                                                  | Placebo.............................................................................................................     | 45                                                                                               |
| 6.3                                                                                                                      | Measures to Minimize Bias: Randomization and Blinding ................................                                   | 45                                                                                               |

| 6.3.2    | Blinding............................................................................................................                       | 46                                                                                                       |
|----------|--------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|
| 6.3.3    | Procedures for Unblinding ................................................................................                                 | 46                                                                                                       |
| 6.4      | Study Intervention Compliance.........................................................................                                     | 47                                                                                                       |
| 6.5      | Concomitant Therapy........................................................................................                                | 47                                                                                                       |
| 6.5.1    | Permitted Concomitant Medications                                                                                                          | ................................................................. 47                                     |
| 6.5.2    | Prohibited Concomitant Medications                                                                                                         | ................................................................ 47                                      |
| 6.6      | Dose Modification                                                                                                                          | ............................................................................................ 48          |
| 6.7      | Intervention After the End of the Study.............................................................                                       | 48                                                                                                       |
| 7        | DISCONTINUATION OF STUDY INTERVENTION AND PARTICIPANT DISCONTINUATION/WITHDRAWAL.......................................................... | 49                                                                                                       |
| 7.1      | Discontinuation of Study Intervention...............................................................                                       | 49                                                                                                       |
| 7.1.1    | Study Suspension or Termination......................................................................                                      | 49                                                                                                       |
| 7.2      | Participant Withdrawal from the Study .............................................................                                        | 50                                                                                                       |
| 7.3      | Lost to Follow-up                                                                                                                          | ............................................................................................. 50         |
| 8        | STUDY ASSESSMENTS AND PROCEDURES                                                                                                           | ............................................. 50                                                         |
| 8.1      | Efficacy Assessments........................................................................................                               | 51                                                                                                       |
| 8.1.1    | Monitoring COVID-19 Symptoms....................................................................                                           | 51                                                                                                       |
| 8.1.2    | Illness Visits                                                                                                                             | ..................................................................................................... 52 |
| 8.1.2.1  | SARS-CoV-2 Testing and Other Virology Assessments....................................                                                      | 53                                                                                                       |
| 8.1.2.2  | Digital Health Device .......................................................................................                              | 53                                                                                                       |
| 8.1.2.3  | Illness e-Diary ..................................................................................................                         | 54                                                                                                       |
| 8.1.3    | Severe COVID-19                                                                                                                            | ............................................................................................ 55          |
| 8.1.4    | Medical Notes Review......................................................................................                                 | 55                                                                                                       |
| 8.1.5    | Monitoring for Asymptomatic Infection............................................................                                          | 55                                                                                                       |
| 8.2      | Safety Assessments...........................................................................................                              | 55                                                                                                       |
| 8.2.1    | Physical Examinations......................................................................................                                | 56                                                                                                       |
| 8.2.2    | Vital Signs........................................................................................................                        | 56                                                                                                       |
| 8.2.3    | Clinical Laboratory Assessments                                                                                                            | ...................................................................... 56                                |
| 8.3      | Adverse Events and Serious Adverse Events.....................................................                                             | 57                                                                                                       |
| 8.3.1    | Time Period and Frequency for Collecting AE and SAE Information................                                                            | 57                                                                                                       |
| 8.3.2    | Follow-up of AEs and SAEs.............................................................................                                     | 57                                                                                                       |
| 8.3.3    | Causality Collection..........................................................................................                             | 58                                                                                                       |
| 8.3.4    | Adverse Events Based on Signs and Symptoms                                                                                                 | ................................................ 59                                                      |
| 8.3.5    | Adverse Events Based on Examinations and Tests............................................                                                 | 59                                                                                                       |
| 8.3.6    | Hy's Law..........................................................................................................                         | 59                                                                                                       |
| 8.3.7    | Solicited Adverse Events (Only for Substudy) ..................................................                                            | 60                                                                                                       |
| 8.3.8    | Medically Attended Adverse Events .................................................................                                        | 61                                                                                                       |
| 8.3.9    | Adverse Events of Special Interest....................................................................                                     | 61                                                                                                       |
| 8.3.9.1  | Potential Neurological AESIs                                                                                                               | ........................................................................... 61                           |
| 8.3.10   | Reporting of Serious Adverse Events................................................................                                        | 63                                                                                                       |
| 8.3.11   | Pregnancy.........................................................................................................                         | 63                                                                                                       |
| 8.3.11.1 | Maternal Exposure............................................................................................                              | 63                                                                                                       |
| 8.3.12   | Medication Error...............................................................................................                            | 64                                                                                                       |

| 8.3.13   | Medical Device Deficiencies.............................................................................                                        | 64                                                                                             |
|----------|-------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
| 8.4      | Overdose ..........................................................................................................                             | 65                                                                                             |
| 8.5      | Human Biological Samples...............................................................................                                         | 65                                                                                             |
| 8.5.1    | Pharmacokinetics..............................................................................................                                  | 65                                                                                             |
| 8.5.2    | Immunogenicity Assessments...........................................................................                                           | 66                                                                                             |
| 8.5.2.1  | SARS-CoV-2 Serology Assessments ................................................................                                                | 66                                                                                             |
| 8.5.2.2  | SARS-CoV-2 Neutralizing Antibody Assessments                                                                                                    | ........................................... 66                                                 |
| 8.5.2.3  | Assessment of Mucosal Responses                                                                                                                 | ................................................................... 66                         |
| 8.5.2.4  | Assessment of Cell-mediated Immune Responses.............................................                                                       | 66                                                                                             |
| 8.5.2.5  | Additional Serum Immunogenicity ...................................................................                                             | 67                                                                                             |
| 8.5.3    | Pharmacodynamics...........................................................................................                                     | 67                                                                                             |
| 8.6      | Human Biological Sample Biomarkers                                                                                                              | ............................................................. 67                               |
| 8.6.1    | Collection of Mandatory Samples for Biomarker Analysis................................                                                          | 67                                                                                             |
| 8.6.1.1  | Virologic Assessments......................................................................................                                     | 67                                                                                             |
| 8.6.1.2  | Assessment of Viral Shedding ..........................................................................                                         | 68                                                                                             |
| 8.6.2    | Other Study-related Biomarker Research ..........................................................                                               | 68                                                                                             |
| 8.7      | Optional Genomics Initiative Sample................................................................                                             | 68                                                                                             |
| 8.8      | Medical Resource Utilization and Health Economics........................................                                                       | 68                                                                                             |
| 9        | STATISTICAL CONSIDERATIONS...............................................................                                                       | 68                                                                                             |
| 9.1      | Statistical Hypotheses.......................................................................................                                   | 68                                                                                             |
| 9.2      | Sample Size Determination...............................................................................                                        | 69                                                                                             |
| 9.3      | Populations for Analyses ..................................................................................                                     | 70                                                                                             |
| 9.4      | Statistical Analyses...........................................................................................                                 | 71                                                                                             |
| 9.4.1    | General Considerations.....................................................................................                                     | 72                                                                                             |
| 9.4.2    | Efficacy ............................................................................................................                           | 73                                                                                             |
| 9.4.2.1  | Primary Endpoint..............................................................................................                                  | 73                                                                                             |
| 9.4.2.2  | Secondary Endpoints ........................................................................................                                    | 75                                                                                             |
| 9.4.2.3  | Exploratory Endpoints                                                                                                                           | ...................................................................................... 77      |
| 9.4.3    | Safety ...............................................................................................................                          | 77                                                                                             |
| 9.4.3.1  | Primary Endpoints ............................................................................................                                  | 77                                                                                             |
| 9.4.3.2  | Other Safety Endpoints.....................................................................................                                     | 77                                                                                             |
| 9.4.4    | Methods for Multiplicity Control                                                                                                                | ...................................................................... 78                      |
| 9.4.5    | Sensitivity Analyses..........................................................................................                                  | 79                                                                                             |
| 9.4.6    | Subgroup Analyses                                                                                                                               | ........................................................................................... 79 |
| 9.5      | Interim Analyses...............................................................................................                                 | 79                                                                                             |
| 9.6      | Data Safety Monitoring Committee...................................................................                                             | 80                                                                                             |
| 10       | SUPPORTING DOCUMENTATION AND OPERATIONAL CONSIDERATIONS........................................................................................ | 80                                                                                             |
| 11       | REFERENCES...............................................................................................                                       | 129                                                                                            |

""",
    """
## LIST OF FIGURES
## LIST OF Golaby

| Figure 1           | Study Design ...........................................................................................                                                                  |   18 |
|--------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|
| Figure 2           | Neurology Testing Algorithm ..................................................................                                                                            |   62 |
| LIST OF TABLES     | LIST OF TABLES                                                                                                                                                            |      |
| Table 1            | Schedule of Activities: Screening Period .................................................                                                                                |   19 |
| Table 2            | Schedule of Activities: Treatment and Follow-up Period - Main Study (Excluding Substudy and Immunogenicity Cohort Participants)...............                            |   20 |
| Table 3            | Schedule of Activities: Treatment and Follow-up Period - Substudy and Immunogenicity Cohort (USA Participants Only).................................... 22                |      |
| Table 4            | Schedule of Activities: Illness Visits (Participants with Qualifying Clinical Symptoms) ................................................................................. |   25 |
| Table 5            | Objectives and Endpoints.........................................................................                                                                         |   30 |
| Table 6            | Highly Effective Methods of Contraception.............................................                                                                                    |   40 |
| Table 7            | Investigational Products...........................................................................                                                                       |   43 |
| Table 8            | List of Predefined Solicited Adverse Events for Reactogenicity Assessment..............................................................................................   |   60 |
| Table 9            | Populations for Analysis ..........................................................................                                                                       |   70 |
| Table 10           | Tables for Clinical Abnormalities: Local Reactions to Injectable Product                                                                                                  |   94 |
| Table 11           | Tables for Clinical Abnormalities: Vital Signs .........................................                                                                                  |   95 |
| Table 12           | Tables for Clinical Abnormalities: Systemic (General or Illness) .............                                                                                            |   96 |
| Table 13           | Adverse Events of Special Interest...........................................................                                                                             |   97 |
| Table 14           | List of Potential Immune-mediated Medical Conditions...........................                                                                                           |   98 |
| Table 15           | Overview of Primary and Secondary Efficacy Objectives, Endpoints, and Associated Case Definitions...................................................................      |  102 |
| LIST OF APPENDICES | LIST OF APPENDICES                                                                                                                                                        |      |
| Appendix A         | Regulatory, Ethical, and Study Oversight Considerations.........................                                                                                          |   81 |
| Appendix B         | Adverse Events: Definitions and Procedures for Recording, Evaluating, Follow-up, and Reporting ........................................................................   |   87 |
| Appendix C         | Handling of Human Biological Samples ..................................................                                                                                   |   91 |
| Appendix D         | Toxicity Grading Scales for Solicited Adverse Events .............................                                                                                        |   93 |
| Appendix E         | Adverse Events of Special Interest...........................................................                                                                             |   97 |
""",
]

for s in sections:
    print(extract_titles(s))
    print("-" * 80)
